-- ==================================================
-- SEED JEE CHAPTERS IN THE DATABASE
-- ==================================================
-- Copy and paste this script into your Supabase SQL Editor
-- (https://supabase.com/dashboard/project/pdnpfpjtbpmuvzopvren/sql)
-- to populate the chapters metadata required for the admin filters.

-- Clear existing chapters first
TRUNCATE TABLE public.chapters CASCADE;

-- Insert chapters (using OVERRIDING SYSTEM VALUE for the GENERATED ALWAYS id column)
INSERT INTO public.chapters (id, chapter_name, subject) OVERRIDING SYSTEM VALUE VALUES 
  -- Physics (1-32)
  (1, 'Math in Physics', 'Physics'),
  (2, 'Units & Dimensions', 'Physics'),
  (3, 'Motion in 1D', 'Physics'),
  (4, 'Motion in 2D', 'Physics'),
  (5, 'Laws of Motion', 'Physics'),
  (6, 'Work Power Energy', 'Physics'),
  (7, 'COM & Collisions', 'Physics'),
  (8, 'Rotational Motion', 'Physics'),
  (9, 'Gravitation', 'Physics'),
  (10, 'Properties of Solids', 'Physics'),
  (11, 'Properties of Fluids', 'Physics'),
  (12, 'Thermal Properties', 'Physics'),
  (13, 'Thermodynamics', 'Physics'),
  (14, 'KTG', 'Physics'),
  (15, 'Oscillations', 'Physics'),
  (16, 'Waves & Sound', 'Physics'),
  (17, 'Electrostatics', 'Physics'),
  (18, 'Capacitance', 'Physics'),
  (19, 'Current Electricity', 'Physics'),
  (20, 'Magnetic Properties', 'Physics'),
  (21, 'Magnetism & Current', 'Physics'),
  (22, 'EMI', 'Physics'),
  (23, 'AC Circuits', 'Physics'),
  (24, 'EM Waves', 'Physics'),
  (25, 'Ray Optics', 'Physics'),
  (26, 'Wave Optics', 'Physics'),
  (27, 'Dual Nature', 'Physics'),
  (28, 'Atomic Physics', 'Physics'),
  (29, 'Nuclear Physics', 'Physics'),
  (30, 'Semiconductors', 'Physics'),
  (31, 'Communication Systems', 'Physics'),
  (32, 'Experimental Physics', 'Physics'),

  -- Chemistry (33-59)
  (33, 'Mole Concept', 'Chemistry'),
  (34, 'Atomic Structure', 'Chemistry'),
  (35, 'Periodic Table', 'Chemistry'),
  (36, 'Chemical Bonding', 'Chemistry'),
  (37, 'States of Matter', 'Chemistry'),
  (38, 'Thermodynamics', 'Chemistry'),
  (39, 'Chemical Equilibrium', 'Chemistry'),
  (40, 'Ionic Equilibrium', 'Chemistry'),
  (41, 'Redox Reaction', 'Chemistry'),
  (42, 'Hydrogen', 'Chemistry'),
  (43, 'S Block', 'Chemistry'),
  (44, 'P Block (13-14)', 'Chemistry'),
  (45, 'General Organic Chemistry (GOC)', 'Chemistry'),
  (46, 'Hydrocarbons', 'Chemistry'),
  (47, 'Solutions', 'Chemistry'),
  (48, 'Electrochemistry', 'Chemistry'),
  (49, 'Chemical Kinetics', 'Chemistry'),
  (50, 'P Block (15-18)', 'Chemistry'),
  (51, 'd & f Block', 'Chemistry'),
  (52, 'Coordination Compounds', 'Chemistry'),
  (53, 'Haloalkanes & Haloarenes', 'Chemistry'),
  (54, 'Alcohols, Phenols & Ethers', 'Chemistry'),
  (55, 'Aldehydes & Ketones', 'Chemistry'),
  (56, 'Carboxylic Acids', 'Chemistry'),
  (57, 'Amines', 'Chemistry'),
  (58, 'Biomolecules', 'Chemistry'),
  (59, 'Practical Chemistry', 'Chemistry'),

  -- Mathematics (60-90)
  (60, 'Basic Mathematics', 'Mathematics'),
  (61, 'Quadratic Equations', 'Mathematics'),
  (62, 'Complex Numbers', 'Mathematics'),
  (63, 'Permutation & Combination', 'Mathematics'),
  (64, 'Sequence & Series', 'Mathematics'),
  (65, 'Binomial Theorem', 'Mathematics'),
  (66, 'Trigonometry', 'Mathematics'),
  (67, 'Trigonometric Equations', 'Mathematics'),
  (68, 'Straight Lines', 'Mathematics'),
  (69, 'Circle', 'Mathematics'),
  (70, 'Parabola', 'Mathematics'),
  (71, 'Ellipse', 'Mathematics'),
  (72, 'Hyperbola', 'Mathematics'),
  (73, 'Limits', 'Mathematics'),
  (74, 'Statistics', 'Mathematics'),
  (75, 'Sets & Relations', 'Mathematics'),
  (76, 'Matrices', 'Mathematics'),
  (77, 'Determinants', 'Mathematics'),
  (78, 'Inverse Trigonometric Functions', 'Mathematics'),
  (79, 'Functions', 'Mathematics'),
  (80, 'Continuity & Differentiability', 'Mathematics'),
  (81, 'Differentiation', 'Mathematics'),
  (82, 'Application of Derivatives', 'Mathematics'),
  (83, 'Indefinite Integration', 'Mathematics'),
  (84, 'Definite Integration', 'Mathematics'),
  (85, 'Area Under Curves', 'Mathematics'),
  (86, 'Differential Equations', 'Mathematics'),
  (87, 'Vector Algebra', 'Mathematics'),
  (88, '3D Geometry', 'Mathematics'),
  (89, 'Linear Programming', 'Mathematics'),
  (90, 'Probability', 'Mathematics');

SELECT * FROM public.chapters ORDER BY id ASC;
